live_config_reload = true
import = [
    "~/.config/alacritty/custom_theme.toml"
]

[colors]
draw_bold_text_with_bright_colors = false

[env]
TERM_PROGRAM = "alacritty"

[font]
size = 13

[font.normal]
family = "RobotoMono Nerd Font Mono"
style = "Medium"
[font.bold]
family = "RobotoMono Nerd Font Mono"
style = "Bold"
[font.italic]
family = "RobotoMono Nerd Font Mono"
style = "Italic"


[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "F"
mods = "Command|Shift"

# [shell]
# program = "/usr/local/bin/tmux"
# args = ["new-session", "-A", "-D", "-s", "main"]

[window]
dynamic_title = true
opacity = 0.9
title = "Terminal"

[window.dimensions]
columns = 150
lines = 40
